//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int stu_id { get; set; }
        public string stu_Name { get; set; }
        public int stu_Num { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
